version: '3.8'

services:
  dev:
    build: .
    container_name: dev_env
    volumes:
      - .:/workspace
    tty: true
    stdin_open: true
    environment:
      - TZ=America/New_York
    working_dir: /workspace

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
